name: Build_x86_64

# Add a button to trigger the workflow
on: 
  repository_dispatch:
  workflow_dispatch:

env:
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Free disk space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Initialization environment
      env:
        TZ: Asia/Shanghai
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -y -qq update
        sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/LeeHe-gif/depend_ubuntu2204_openwrt/refs/heads/main/depend_ubuntu2204_openwrt)
        sudo -E systemctl daemon-reload
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo timedatectl set-timezone "${TZ}"
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        
    - name: Free up disk space
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p -m 777 /mnt/openwrt/dl /mnt/openwrt/staging_dir /mnt/openwrt/build_dir
        ln -sf /mnt/openwrt/dl openwrt/dl
        ln -sf /mnt/openwrt/staging_dir openwrt/staging_dir
        ln -sf /mnt/openwrt/build_dir openwrt/build_dir

    - name: Configuration Customization - Build_x86_64
      env:
        CONFIG_FILE: 'x86_64.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
    - name: Update and Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        sleep 5
        ./scripts/feeds install -a
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the OpenWrt
      id: compile
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) | tee log.txt
        echo "status=success" >> ${GITHUB_OUTPUT}
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        
    - name: Check space usage
      if: (!cancelled())
      run: df -hT       

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && steps.compile.outputs.status == 'success' 
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: copy log
      id: log
      continue-on-error: true
      if: steps.compile.outputs.status != 'success'
      run: |
        cd openwrt
        cp log.txt bin/targets/*/*/log.txt
        cd bin/targets/*/*
        rm feeds.buildinfo
        rm version.buildinfo
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload artifact
      id: artifact
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
 
    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success'
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        echo -e "##### OpenWrt 固件信息 \n- 使用lede的源码 \n- 默认网关: 192.168.10.1 \n- 默认用户: root \n- 默认密码: password \n- 已装插件:-luci-app-accesscontrol=y \n \t-luci-app-adbyby-plus=y \n \t-luci-app-adguardhome=y \n \t-luci-app-airplay2=y \n \t-luci-app-alist=y \n \t-luci-app-argon-config=y \n \t-luci-app-aria2=y \n \t-luci-app-autoreboot=y \n \t-luci-app-commands=y \n \t-luci-app-ddns=y \n \t-luci-app-diskman=y \n \t-luci-app-dockerman=y \n \t-luci-app-filebrowser=y \n \t-luci-app-filetransfer=y \n \t-luci-app-firewall=y \n \t-luci-app-hd-idle=y \n \t-luci-app-minidlna=y \n \t-luci-app-mwan3=y \n \t-luci-app-nlbwmon=y \n \t-luci-app-onliner=y \n \t-luci-app-openclash=y \n \t-luci-app-poweroff=y \n \t-luci-app-pptp-server=y \n \t-luci-app-pushbot=y \n \t-luci-app-qbittorrent=y \n \t-luci-app-samba4=y \n \t-luci-app-serverchan=y \n \t-luci-app-ttyd=y \n \t-luci-app-turboacc=y \n \t-luci-app-upnp=y \n \t-luci-app-v2ray-server=y \n \t-luci-app-wol=y \n \t-luci-app-wrtbwmon=y \n \t" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Generate failed release tag
      id: ftag
      if: steps.log.outputs.status == 'success'
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT       
        touch release.txt
        echo "编译失败，请查看log.txt编译日志排查原因" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: Upload log to release
      uses: softprops/action-gh-release@v1
      if: steps.ftag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.ftag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*


    - name: Delete workflow runs
      uses: LeeHe-gif/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
        token: ${{ secrets.GITHUB_TOKEN }}
